### PR TITLE
Use Enterprise Code™

### PR DESCRIPTION
**Pull request by samczsun**
This will guarantee that investors will be impressed by your code.

### CODE REVIEW

**Comment by devmattrick** [comment]
+1

**Comment by stuntguy3000** [comment]
Please perform a cost benefit analysis about this request.

Also, we need testing protocols.

Please review at next meeting.

**Comment by samczsun** [comment]
First we need to schedule a meeting to discussing the review meeting. Can we discuss a time to schedule the meeting for discussing the review meeting sometime soon?

**Comment by 1Rogue** [comment]
Can you make the enterprising _more_ enterprised? We talked about this at the meeting meeting on Wednesday's meeting about enterprise meetings.

**Comment by stuntguy3000** [comment]
Agreed, will investigate @1Rogue. I will pass the details along to HR and Marketing to invest into better meetings.

**Comment by stuntguy3000** [comment]
Agreed, will investigate @1Rogue. I will pass the details along to HR and Marketing to invest into better meetings.

**Comment by stuntguy3000** [comment]
Reporting you to GitHub Enterprise Solutions.

HR will be aware of this rogue behavior.

**Pull request closed without merging**
